In [2]:
import pandas as pd
df = pd.read_csv('data/raw/chess_games.csv')

In [3]:
df.head()

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
0,1,False,13,Out of Time,White,15+2,bourgris,1500,a-00,1191,d4 d5 c4 c6 cxd5 e6 dxe6 fxe6 Nf3 Bb4+ Nc3 Ba5...,D10,5,Slav Defense: Exchange Variation,Slav Defense,NaN,Exchange Variation
1,2,True,16,Resign,Black,5+10,a-00,1322,skinnerua,1261,d4 Nc6 e4 e5 f4 f6 dxe5 fxe5 fxe5 Nxe5 Qd4 Nc6...,B00,4,Nimzowitsch Defense: Kennedy Variation,Nimzowitsch Defense,NaN,Kennedy Variation
2,3,True,61,Mate,White,5+10,ischia,1496,a-00,1500,e4 e5 d3 d6 Be3 c6 Be2 b5 Nd2 a5 a4 c5 axb5 Nc...,C20,3,King's Pawn Game: Leonardis Variation,King's Pawn Game,NaN,Leonardis Variation
3,4,True,61,Mate,White,20+0,daniamurashov,1439,adivanov2009,1454,d4 d5 Nf3 Bf5 Nc3 Nf6 Bf4 Ng4 e3 Nc6 Be2 Qd7 O...,D02,3,Queen's Pawn Game: Zukertort Variation,Queen's Pawn Game,NaN,Zukertort Variation
4,5,True,95,Mate,White,30+3,nik221107,1523,adivanov2009,1469,e4 e5 Nf3 d6 d4 Nc6 d5 Nb4 a3 Na6 Nc3 Be7 b4 N...,C41,5,Philidor Defense,Philidor Defense,NaN,NaN

In [4]:
df.shape

(20058, 17)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.columns.tolist()

['game_id',
 'rated',
 'turns',
 'victory_status',
 'winner',
 'time_increment',
 'white_id',
 'white_rating',
 'black_id',
 'black_rating',
 'moves',
 'opening_code',
 'opening_moves',
 'opening_fullname',
 'opening_shortname',
 'opening_response',
 'opening_variation']

In [7]:
df['moves'].duplicated().sum()

np.int64(1138)

In [8]:
df['opening_response'].isna().mean() * 100

np.float64(93.982450892412)

In [9]:
df['opening_variation'].isna().mean() * 100

np.float64(28.218167314787117)

In [10]:
df['turns'].min()

np.int64(1)

In [11]:
df[df['turns'] == df['turns'].min()]

,game_id,rated,turns,victory_status,winner,time_increment,white_id,white_rating,black_id,black_rating,moves,opening_code,opening_moves,opening_fullname,opening_shortname,opening_response,opening_variation
1946,1947,True,1,Resign,Black,10+0,serik-astana,1464,brorael357,1355,g3,A00,1,Hungarian Opening,Hungarian Opening,NaN,NaN
1977,1978,False,1,Out of Time,White,10+60,clarkkent89,2032,tactical_bishop,1223,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
4115,4116,False,1,Out of Time,White,5+15,fairygirl,2404,oreo_or_orion,1616,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
4473,4474,False,1,Out of Time,White,5+5,ranchowangdu,1500,justicebot,2723,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
4828,4829,True,1,Resign,White,10+0,bert-w,1670,andreschil,1175,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
5496,5497,False,1,Out of Time,White,5+15,slowgamer,2100,ytdvvc,1404,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
5875,5876,True,1,Resign,White,10+0,buglkraxnseppl,1778,kellyclarkson,1349,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
6040,6041,False,1,Out of Time,White,60+60,lance5500,2617,justindong,1500,Nf3,A04,1,Reti Opening,Reti Opening,NaN,NaN
9229,9230,True,1,Resign,White,10+0,keeperpine,1484,raesremmurd,2113,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
11742,11743,False,1,Resign,White,10+25,lance5500,2621,antons,1614,d4,A40,1,Queen's Pawn,Queen's Pawn,NaN,NaN
11963,11964,False,1,Out of Time,White,15+30,critico-82,2403,lesauteurdeclasse,1746,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
12679,12680,False,1,Out of Time,White,5+60,lance5500,2621,raulelbueno,1384,d4,A40,1,Queen's Pawn,Queen's Pawn,NaN,NaN
13557,13558,False,1,Out of Time,White,20+10,jerusseust,2438,palermagno,1666,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
13560,13561,False,1,Out of Time,White,20+10,jerusseust,2438,castlebit,1885,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
13701,13702,True,1,Resign,Black,10+0,networkchess2,1878,kaskade24,1860,d3,A00,1,Mieses Opening,Mieses Opening,NaN,NaN
14117,14118,False,1,Out of Time,White,10+20,lance5500,2621,xxcrunchypebblexx,1324,d4,A40,1,Queen's Pawn,Queen's Pawn,NaN,NaN
15007,15008,False,1,Out of Time,White,15+30,critico-82,2403,lesauteurdeclasse,1746,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN
18583,18584,True,1,Resign,White,10+0,adriansywu,1431,usa-04071776,1367,e4,B00,1,King's Pawn,King's Pawn,NaN,NaN